name: CI/CD Pipeline
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Application has been built successfully"
  sonarlint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Code has passed SonarLint checks"
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Code has passed Checkstyle tests"
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Code has passed unit tests"

